services:
  - type: web
    name: blogcopy
    env: python
    buildCommand: ./build.sh
    startCommand: cd my_blog && python manage.py migrate --noinput && gunicorn my_blog.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: DB_SSL_REQUIRE
        value: "True"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
